### ISSUE TITLE
mupen86 status and future

### ISSUE THREAD

**Issue by mckaygerhard** [cxd4/mupen86#2]
there's no recents commits and exists mupen64plus.. so due that the question here!

1. What is the status of the project?
2. What are the purpose of the code if there exists mupen64plus?
3. The Opengl deénds will need a very modern or i can play at my minilaptop?

some time ago i upload the mupen64 code and commits some fixeds but i do not have enought skills and do no solved all the problems with the emulator.. then mupen64plus comes.. but! today that emulator requires too many resources to play! that sound ilogic for me!

NOTE: I think that being a mathematical person you will have in mind that it is illogical that a machine of more than 2GHz is needed to play one of only 133MHz, i mean...

**Comment by cxd4** [comment]
The status is that I work on it whenever there is anything additional I want to tweak about it.

It is just my own personal fork of the original Mupen64 where I have added proper 64-bit support and for 64-bit zilmar-spec plugins, which Mupen64 "Plus" never truly achieved.  Sometimes I find and fix bugs, but I do not invest much time in that.

**Comment by mckaygerhard** [comment]
thanks for explain so i try to build and contribute it .. some of my guys need in alpine and debian older (kernel 2.6.38)..

**Comment by cxd4** [comment]
Shouldn't matter.  The build script `make.sh` was designed to work on UNIX in general; should work all the same on any version of the kernel Linux.
